### PR TITLE
AUR pkgbuild cleanup

### PR DESCRIPTION
**Pull request by FabioLolix**
Removed unneeded variables and double source. proper pkgker(), epoch addition was necessary

### CODE REVIEW

**Comment by tyzoid** [comment]
:+1: from me. I like clean pkgbuilds.

**Comment by lsmith77** [comment]
right now when I install screenrotator-git via AUR I always get this package listed under "updates". Would this PR fix this?

**Comment by FabioLolix** [comment]
@lsmith77 yes, this have a sane pkgver()

**Comment by lsmith77** [comment]
thx!

**Pull request merged**
